<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
	<PropertyGroup>
		<TargetFramework>net10.0-browser</TargetFramework>
		<OutputType>Exe</OutputType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Browser" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Kokkoro\Kokkoro.csproj" />
	</ItemGroup>
</Project>
